### ISSUE TITLE
Will create C:\Users\<username>\AppData\Roaming\marktext\Dictionaries folder

### ISSUE THREAD

**Issue by innocentliny** [jgonyea/Mark-Text-Portable#1]
Hi,

Thank you for providing portable version.

- OS: Windows 10
- Description
   I notice that folder ```C:\Users\<username>\AppData\Roaming\marktext\Dictionaries``` will be created after MarkText launched, even manually delete this folder.
- Anticipation
   Such folders should be only created in portable MarkText folder.

Thank you.

**Comment by jgonyea** [comment]
I can't prevent the app from creating the folder, but I might be able to get it to delete the folder afterwards.  Thanks for the heads up.

**Comment by jgonyea** [comment]
Reopening so I can track this issue.

**Comment by jgonyea** [comment]
Fixed in latest build.
